---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: kubearmor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: kubearmor
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /var/lib/grafana/plugins/accuknox-kubearmor-datasource
              name: plugin-volume
            - mountPath: /etc/grafana/provisioning
              name: provisioning-volume
            - mountPath: /root/accuknox-kubearmor-datasource
              name: source-code
          env:
            - name: NODE_ENV
              value: "development"
            - name: GF_LOG_FILTERS
              value: "plugin.accuknox-kubearmor-datasource:debug"
            - name: GF_LOG_LEVEL
              value: "debug"
            - name: GF_DATAPROXY_LOGGING
              value: "1"
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: "accuknox-kubearmor-datasource"
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: plugin-volume
          hostPath:
            path: /home/hari/opensource/accuknox-kubearmor-datasource/dist
        - name: provisioning-volume
          hostPath:
            path: /home/hari/opensource/accuknox-kubearmor-datasource/provisioning
        - name: source-code
          hostPath:
            path: /home/hari/opensource/accuknox-kubearmor-datasource
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kubearmor
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
