apiVersion: operator.kubearmor.com/v1
kind: KubeArmorConfig
metadata:
  labels:
    app.kubernetes.io/name: kubearmorconfig
    app.kubernetes.io/instance: kubearmorconfig-sample
    app.kubernetes.io/part-of: kubearmoroperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubearmoroperator
  name: kubearmorconfig-default
  namespace: kubearmor
spec:
  defaultCapabilitiesPosture: audit
  defaultFilePosture: audit
  defaultNetworkPosture: audit
  defaultVisibility: process,network
  enableStdOutLogs: false
  enableStdOutAlerts: false
  enableStdOutMsgs: false
  seccompEnabled: false
  kubearmorImage:
    image: kubearmor/kubearmor:stable
    imagePullPolicy: Always
  kubearmorInitImage:
    image: kubearmor/kubearmor-init:stable
    imagePullPolicy: Always
  # kubearmorRelayImage:
  #   image: harisudarsan/kubearmor-relay-server:1.0.1
  #   imagePullPolicy: Always
  #   env:
  #     - name: ENABLE_DASHBOARDS
  #       value: "true"
  #     - name: ES_URL
  #       value: "http://elasticsearch:9200"
  #     - name: KUBEARMOR_SERVICE
  #       value: ""
  #     - name: ENABLE_STDOUT_LOGS
  #       value: "false"
  #     - name: ENABLE_STDOUT_ALERTS
  #       value: "false"
  #     - name: ENABLE_STDOUT_MSGS
  #       value: "false"

  kubearmorControllerImage:
    image: kubearmor/kubearmor-controller
    imagePullPolicy: Always
